compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@docusaurus/preset-classic@*":
    dependencies:
      "@docusaurus/theme-common": 2.0.0-beta.14
  "@docusaurus/theme-classic@*":
    peerDependencies:
      "@docusaurus/theme-common": "*"
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@docusaurus/theme-common": "*"
  terser@*:
    dependencies:
      acorn: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
