nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "@docusaurus/preset-classic@*":
    dependencies:
      "@docusaurus/theme-common": "2.0.0-beta.14"
  "@docusaurus/theme-classic@*":
    peerDependencies:
      "@docusaurus/theme-common": "*"
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@docusaurus/theme-common": "*"
  "terser@*":
    dependencies:
      acorn: "*"
